### ISSUE TITLE
Receiving 'cannot find module error' after upgrading from 0.3.8 to 0.3.12

### ISSUE THREAD

**Issue by RuXxar** [sebastian-lenz/typedoc#157]
I was previously able to include the typings reference file as one of the sources fed into typedoc and compile the documentation without errors.
Example:

```
gulp.task('autogendoc', function () {
  return gulp
      .src(['./components/api/*.ts', './typings/references.d.ts'])
      .pipe(plugins.typedoc({
        module: 'commonjs',
        target: 'es5',
        json: './dist/documentation/autogen.json',
        name: 'xxx',
        ignoreCompilerErrors: false,
        excludeExternals: true
      }))
});
```

However, after updating typedoc from version 0.3.8 to version 0.3.12 I'm getting a lot of 'cannot find module' errors from the API source files.

**Comment by sebastian-lenz** [comment]
Could you provide some detailed information, which modules could not be found? I ran into a lot of issues after the latest update of Node, did you try to do a clean install?

**Comment by RuXxar** [comment]
My errors go away when I run the latest repository version 0.4.0. I hope it gets released soon,
